#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail
set -o xtrace

readonly TARGET_HOST=hopper.local
readonly TARGET_PATH=/home/dweis/hopper_face_simple
readonly TARGET_ARCH=armv7-unknown-linux-musleabihf
readonly SOURCE_PATH=./target/${TARGET_ARCH}/release/simple

cargo build --release --target=${TARGET_ARCH} 
